version: "3.9"

services:
  api:
    build:
      context: ./monitoring-system-backend   # adjust path to your Go project
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=
      - CHECK_TIMER= 6000
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_EMAIL_FROM=
      - GITLAB_TOKEN=
    networks:
      - app-network

  frontend:
    build:
      context: ./monitoring-system
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
      - VITE_WEBSOCKET_URL=ws://localhost:8000
      - VITE_APP_TITLE=Monitoring System
      - VITE_API_BASE_URL_WEB_SOCKET=http://localhost:8080/api/v1
      - BROWSER=none
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
